문법

In [ ]:
import numpy as np 
a = np.arange(9).reshape(3,3) 
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
a[1, :]

array([3, 4, 5])

(4, 3, 2) 크기의 배열은 (3,2) 크기의 배열이 4개 있는 리스트

In [13]:
a = np.array([[1,2], [2,3], [4,5]])
len(a)

3

QUIZ

In [ ]:
a = np.arange(6).reshape(3,2,1) #2x1 3겹
b = a[0]    
c = a[:2, 0]
d = a[0, :, 0]

print(b)
print(c)
print(d)

[[0]
 [1]]
[[0]
 [2]]
[0 1]


a =
[
  [ [0],
    [1] ],   ← a[0]

  [ [2],
    [3] ],   ← a[1]

  [ [4],
    [5] ]    ← a[2]
]

c = a[:2, 0] -> a[0],a[1] 겹 + 각 겹의 0번째 행
d = a[0, : , 0] -> a[0]겹 + 각 겹의 전체 + 값만 꺼내기

In [28]:
a = np.arange(24).reshape(2, 4, 1, 3) #4x1x3 2겹
# 1
b = a[:, 0]
c = a[0, :, :1, 0]  # 겹 줄 세로 채널
d = a[1, 1, 0]
e = a[:, 1:, 0, 2]

print(b)
print()

print(c)
print()

print(d)
print()

print(e)
print()


[[[ 0  1  2]]

 [[12 13 14]]]

[[0]
 [3]
 [6]
 [9]]

[15 16 17]

[[ 5  8 11]
 [17 20 23]]



a =
[
  [                   ← 첫 번째 큰 묶음 (a[0])
    [[0, 1, 2]],
    [[3, 4, 5]],       (1x3) 4겹
    [[6, 7, 8]],
    [[9,10,11]]
  ],

  [                   ← 두 번째 큰 묶음 (a[1])
    [[12,13,14]],
    [[15,16,17]],
    [[18,19,20]],
    [[21,22,23]]
  ]
]


In [37]:
a = np.array([[1,2,3], [4,5,6]])

a[1, :]

array([4, 5, 6])

In [ ]:
 2